name: POC
on: push
jobs:
  prepare: 
    runs-on: ubuntu-latest
    steps:
      - run: echo prepare
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - run: |
          echo build
          sleep 20
          exit 2
        shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo deploy
        shell: bash

  retry:
    runs-on: ubuntu-latest
    needs: [prepare, build, deploy]
    if: ${{ always() }}
    steps:
      - run: echo retry
        shell: bash
  
