name: trigger rerun

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Rerun workflow id'
        required: true

jobs:
  prepare: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rerun Workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run rerun ${{ github.event.inputs.run_id }} --failed
